### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by pql123** [thevoidname/Generalized-One-shot-GAN-Adaption#7]
when i run train_OSGA.sh by gpu， i receive this trace， how i fix this？

Traceback (most recent call last):
  File "generalized_one_shot_adaption.py", line 401, in <module>
    train_function(config)
  File "generalized_one_shot_adaption.py", line 343, in train_function
    domain_adaption.process(ws, images, masks, config)
  File "generalized_one_shot_adaption.py", line 216, in process
    **config.synthesis_kwargs)
  File "/home/pql/generalized-one-shot-gan-adaptation/inversion_networks_utils.py", line 126, in synthesis_aux_forward
    x, img = block(x, img, cur_ws, **kwargs)
  File "/home/pql/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 397, in forward
  File "/home/pql/anaconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 292, in forward
  File "/home/pql/generalized-one-shot-gan-adaptation/torch_utils/misc.py", line 104, in decorator
    return fn(*args, **kwargs)
  File "<string>", line 72, in modulated_conv2d
  File "/home/pql/generalized-one-shot-gan-adaptation/torch_utils/misc.py", line 104, in decorator
    return fn(*args, **kwargs)
  File "/home/pql/generalized-one-shot-gan-adaptation/torch_utils/ops/conv2d_resample.py", line 126, in conv2d_resample
    x = upfirdn2d.upfirdn2d(x=x, f=f, padding=[px0+pxt,px1+pxt,py0+pyt,py1+pyt], gain=up**2, flip_filter=flip_filter)
  File "/home/pql/generalized-one-shot-gan-adaptation/torch_utils/ops/upfirdn2d.py", line 161, in upfirdn2d
    return _upfirdn2d_cuda(up=up, down=down, padding=padding, flip_filter=flip_filter, gain=gain).apply(x, f)
  File "/home/pql/generalized-one-shot-gan-adaptation/torch_utils/ops/upfirdn2d.py", line 242, in forward
    y = _plugin.upfirdn2d(y, f, upx, upy, downx, downy, padx0, padx1, pady0, pady1, flip_filter, gain)

**Comment by zhangzc21** [comment]
Hi, it looks like the Cuda operators in StyleGAN2 are not compiled correctly. Please follow the guidance in the official StyleGAN2 repository to reinstall the environment.

**Comment by pql123** [comment]
thanks, i will try to reinstall the environment
